### ISSUE TITLE
Firefox input fields color

### ISSUE THREAD

**Issue by alexfalcucci** [EliverLara/Ant#25]
Hey there, there is a problem with the color of the inputs that I think should be fixed.

The issue is happening only in Firefox for now cuz it uses the default buttons of the system (seems like, it's just a thought idk, on chrome the overlaps doesn't happen). So once that I am using Firefox this is extremely uncomfortable in terms of the user experience.

Is there any way to fix it and stop to overlap the button colors in Firefox? Only the buttons =)

![](https://screenshots.firefoxusercontent.com/images/1d04a410-2603-43e5-b074-340ab87bd50c.png)

OS: `Ubuntu 14.04`
Theme: `Ant-Dracula`

**Comment by alexfalcucc** [comment]
I've fixed changing https://github.com/EliverLara/Ant/blob/master/gtk-3.0/gtk-widgets.css#L366-L369
to: 
```css
.view {
    background-color: #FFF;
    color: @base_color;
}


```
but the issue is in the `Ant-Dracula` theme. I could send a pull request but i don't know where is the repo for this theme.

**Comment by EliverLara** [comment]
You're right, but that solution has side effects in the UI, anyway I've already commented on this before but apparently the user deleted the issue, I proposed as a temporary solution to install the [Text Contrast for Dark Themes](https://addons.mozilla.org/en-US/firefox/addon/text-contrast-for-dark-themes/) addon for firefox, because apparently it's an old firefox issue with dark themes, as you can see in [this](https://github.com/horst3180/arc-theme/issues/761) thread from the Arc theme.

**Comment by alexfalcucc** [comment]
I see now, thanks for your recommendation but the extension doesn't solved the problem. So I`ll keep this "manual" change for now, while we don't have news from Mozilla to fix it.

**Comment by sebdah** [comment]
I have the same issue with the Dracula theme. Bloody works just fine. The proposed Firefox plugin does not solve the issue for me either unfortunately. 

For now I'll reside to Bloody.

**Comment by sebdah** [comment]
I'm on Arch Linux with Gnome.

**Comment by dinojr** [comment]
The firefox plugin fixes the php input fields at least. I also noticed that the gnome web browser exhibits the same problem.
